# file: .github/workflows/deploy-next-app.yml
#
# Deploys the Next.js app to GCP Cloud Run.
#

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} # service account key
  GCP_REGION: us-east4 # service location
  GCP_SERVICE: udon-website # Cloud Run service name

jobs:
  build-and-deploy:
    name: Build and Deploy Next.js App
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/authenticate-to-google-cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_SERVICE }}:${{ github.sha }} .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_SERVICE }}:${{ github.sha }}

      # https://github.com/marketplace/actions/deploy-to-cloud-run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.GCP_SERVICE }}
          image: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_SERVICE }}:${{ github.sha }}
          region: ${{ env.GCP_REGION }}
          flags: --allow-unauthenticated

      - name: Print URL
        run: echo ${{ steps.deploy.outputs.url }}
#
# end of file: .github/workflows/deploy-next-app.yml
